# -*- coding: utf-8 -*-
"""youssefCVtask.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W77PFJyuVX2fWXLn8LziU1TmnNFsRIOO

# Libraries
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, models
import matplotlib.pyplot as plt
import seaborn as sns
from PIL import Image
import os

"""# Seeds"""

SEED = 69
ENABLE_DETERMINISM = True

import os
os.environ['PYTHONHASHSEED'] = f'{SEED}'
os.environ['TF_DETERMINISTIC_OPS'] = f'{ENABLE_DETERMINISM}'
os.environ['TF_CUDNN_DETERMINISTIC'] = f'{ENABLE_DETERMINISM}'

import random
import numpy as np
import tensorflow as tf
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

"""# Downloading Data"""

!pip install -q kaggle
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

#!/bin/bash
!kaggle datasets download karimabdulnabi/fruit-classification10-class

import zipfile

with zipfile.ZipFile("/content/fruit-classification10-class.zip", 'r') as zip_ref:
    zip_ref.extractall("/content/fruit_images")

train_dir = "/content/fruit_images/MY_data/train"
test_dir = "/content/fruit_images/MY_data/test"

"""# Data Exploration"""

classes = os.listdir(train_dir)
plt.figure(figsize=(15, 6))

for i, cls in enumerate(classes):
    img_name = random.choice(os.listdir(os.path.join(train_dir, cls)))
    img_path = os.path.join(train_dir, cls, img_name)
    img = Image.open(img_path)

    plt.subplot(2, 5, i+1)
    plt.imshow(img)
    plt.title(cls)
    plt.axis("off")

plt.show()

def count_images(data_dir):
    class_counts = {}

    for class_name in os.listdir(data_dir):
        class_dir=os.path.join(data_dir,class_name)

        if os.path.isdir(class_dir):
            num_images = len(os.listdir(class_dir))
            class_counts[class_name] = num_images

    return class_counts

train_counts = count_images(train_dir)
test_counts  = count_images(test_dir)

print("Training set distribution:")
print(train_counts)

print("\nTest set distribution:")
print(test_counts)

plt.figure(figsize=(10,5))
plt.bar(train_counts.keys(), train_counts.values(), color=sns.color_palette("rocket", len(train_counts)))
plt.xticks(rotation=45)
plt.title("Training Set Class Distribution")
plt.show()

plt.figure(figsize=(10,5))
plt.bar(test_counts.keys(), test_counts.values(), color=sns.color_palette("rocket", len(test_counts)))
plt.xticks(rotation=45)
plt.title("Testing Set Class Distribution")
plt.show()

def check_image_sizes(data_dir, num_samples=50):
    sizes = []

    for cls in os.listdir(data_dir):
        cls_path = os.path.join(data_dir, cls)

        images = os.listdir(cls_path)
        sample_images = random.sample(images, min(num_samples, len(images)))

        for img_name in sample_images:
            img_path = os.path.join(cls_path, img_name)

            try:
                with Image.open(img_path) as img:
                    sizes.append(img.size)
            except:
                pass
    return sizes

sizes = check_image_sizes(train_dir)
unique_sizes = set(sizes)

max_width = max(w for w, h in sizes)
max_height = max(h for w, h in sizes)

print("Max width:", max_width)
print("Max height:", max_height)

max_size = max(sizes, key=lambda s: s[0] * s[1])

print("Largest resolution:", max_size)
print("Total pixels:", max_size[0] * max_size[1])

print("Unique image sizes found:")
print(unique_sizes)

def check_image_modes(data_dir, num_samples=20):
    modes = set()

    for cls in os.listdir(data_dir):
        cls_path = os.path.join(data_dir, cls)
        images = os.listdir(cls_path)

        for img_name in images[:num_samples]:
            img_path = os.path.join(cls_path, img_name)

            try:
                with Image.open(img_path) as img:
                    modes.add(img.mode)
            except:
                pass
    return modes

modes = check_image_modes(train_dir)
print("Image Modes:", modes)

def check_formats(data_dir):
    formats = set()

    for cls in os.listdir(data_dir):
        cls_path = os.path.join(data_dir, cls)

        for img_name in os.listdir(cls_path):
            ext = os.path.splitext(img_name)[1]
            formats.add(ext.lower())

    return formats

formats = check_formats(train_dir)
print("Image Formats:", formats)

def find_corrupted_images(data_dir):
    corrupted = []

    for cls in os.listdir(data_dir):
        cls_path = os.path.join(data_dir, cls)

        for img_name in os.listdir(cls_path):
            img_path = os.path.join(cls_path, img_name)

            try:
                with Image.open(img_path) as img:
                    img.verify()
            except:
                corrupted.append(img_path)

    return corrupted

corrupted_images = find_corrupted_images(train_dir)
print("Number of corrupted images:", len(corrupted_images))

"""# Data Division & Augmentation"""

IMG_SIZE = (455,320)
BATCH_SIZE = 32

train_ds = tf.keras.utils.image_dataset_from_directory(
    train_dir,
    validation_split=0.2,
    subset="training",
    seed=42,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

val_ds = tf.keras.utils.image_dataset_from_directory(
    train_dir,
    validation_split=0.2,
    subset="validation",
    seed=42,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

test_ds = tf.keras.utils.image_dataset_from_directory(
    test_dir,
    image_size=IMG_SIZE,
    batch_size=BATCH_SIZE
)

class_names = train_ds.class_names
print("Classes:", class_names)

data_augmentation = keras.Sequential([
    layers.RandomFlip("horizontal"),
    layers.RandomRotation(0.1),
    layers.RandomZoom(0.1),
    layers.Cropping2D(cropping=((10, 10), (10, 10))),
    layers.Resizing(224, 224)
])

"""# Model Architecture & Training"""

def build_model(input_shape=(455,320,3), num_classes=10):

    inputs = layers.Input(shape=input_shape)

    # augmentation
    x = data_augmentation(inputs)

    # Normalize pixels
    x = layers.Rescaling(1./255)(x)

    # CNN
    x = layers.Conv2D(32, (3,3), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D()(x)

    x = layers.Conv2D(64, (3,3), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D()(x)

    x = layers.Conv2D(128, (3,3), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D()(x)

    x = layers.Conv2D(256, (3,3), padding='same')(x)
    x = layers.BatchNormalization()(x)
    x = layers.ReLU()(x)
    x = layers.MaxPooling2D()(x)

    x = layers.GlobalAveragePooling2D()(x)

    outputs = layers.Dense(num_classes, activation='softmax')(x)

    model = models.Model(inputs, outputs)
    return model


model = build_model(num_classes=10)
model.summary()

model.compile(
    optimizer="adam",
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

callbacks = [
    tf.keras.callbacks.EarlyStopping(
        patience=10,
        restore_best_weights=True
    ),
    tf.keras.callbacks.ReduceLROnPlateau(
        factor=0.5,
        patience=5
    )
]

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=50,
    callbacks=callbacks
)

test_loss, test_acc = model.evaluate(test_ds)

print("Test Accuracy:", test_acc)

acc = history.history["accuracy"]
val_acc = history.history["val_accuracy"]

loss = history.history["loss"]
val_loss = history.history["val_loss"]

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.plot(acc,label="Train Accuracy")
plt.plot(val_acc,label="Validation Accuracy")
plt.legend()
plt.title("Accuracy")

plt.subplot(1,2,2)
plt.plot(loss,label="Train Loss")
plt.plot(val_loss,label="Validation Loss")
plt.legend()
plt.title("Loss")

plt.show()